# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_writer')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_writer')
    _writer = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_writer', [dirname(__file__)])
        except ImportError:
            import _writer
            return _writer
        try:
            _mod = imp.load_module('_writer', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _writer = swig_import_helper()
    del swig_import_helper
else:
    import _writer
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def get_parsed_json(fileName: 'std::string const') -> "nlohmann::json":
    return _writer.get_parsed_json(fileName)
get_parsed_json = _writer.get_parsed_json

def has_advantage(age: 'int const') -> "bool":
    return _writer.has_advantage(age)
has_advantage = _writer.has_advantage

def calculate_score(arg: 'void *') -> "void *":
    return _writer.calculate_score(arg)
calculate_score = _writer.calculate_score

def get_scores(jsonArr: 'nlohmann::json') -> "std::vector< nlohmann::json >":
    return _writer.get_scores(jsonArr)
get_scores = _writer.get_scores

def write_json_file(readFile: 'std::string const', writeFile: 'std::string const') -> "void":
    return _writer.write_json_file(readFile, writeFile)
write_json_file = _writer.write_json_file

def execute() -> "void":
    return _writer.execute()
execute = _writer.execute
# This file is compatible with both classic and new-style classes.

cvar = _writer.cvar

